name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Build app
      run: scripts/buildprod.sh

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Use gcloud CLI
      run: gcloud info

    - name: Build and push to Docker image
      run: gcloud builds submit --tag europe-central2-docker.pkg.dev/notely-432422/notely-ar-repo/notely:latest .

    - name: Install goose
      run: go install github.com/pressly/goose/v3/cmd/goose@latest

    - name: Run migrations
      run: ./scripts/migrateup.sh

    - name: Deploy to Cloud Run
      run: gcloud run deploy notely --image europe-central2-docker.pkg.dev/notely-432422/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-432422 --max-instances=4